apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-tiwznf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-tiwznf
    app.kubernetes.io/part-of: jvm-build-suite-application-hdyk
  name: jvm-build-suite-component-tiwznf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-tiwznf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-tiwznf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-qfwm-tenant/jvm-build-suite-application-hdyk/jvm-build-suite-component-tiwznf@sha256:43f9f7aafaafbca675b7163f32428778b38f53607f9ffd43390720e44b3a0074
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
